server.port=8080
resources.folder=D:\\test
resources.contextPath=/resources

redis.host=127.0.0.1
redis.password=123456

cookie.expire=86400

mybatis.environment.id=development
JDBC.driver=com.mysql.cj.jdbc.Driver
JDBC.url=jdbc:mysql://192.168.1.111:3306/ultimate?serverTimezone=UTC&characterEncoding=utf-8
JDBC.username=root
JDBC.password=123456